BooksStore.Web/Areas/Admin/Controllers/UserController.cs
using BooksStore.DataAccess.Database;
using BooksStore.Models;
using BooksStore.Models.ViewModels;
using BooksStore.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BooksStore.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles = StaticDetails.Role_Admin)]
    //[Authorize]
    [Route("[area]/[controller]")]
    public class UserController : Controller
    {
        private readonly BooksStoreDbContext _db;
        private readonly ILogger<UserController> _logger;
        private readonly UserManager<IdentityUser> _userManager;
        public UserController(BooksStoreDbContext db, ILogger<UserController> logger, UserManager<IdentityUser> userManager)
        {
            this._db = db;
            this._logger = logger;
            this._userManager = userManager;
        }

        [HttpGet]
        [Route("[action]")]
        public IActionResult Index()
        {
            this._logger.LogInformation("{ControllerName}.{MethodName} action get method",
                nameof(UserController), nameof(this.Index));

            return this.View();
        }

        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> RoleManagement([FromQuery] string? userId)
        {
            this._logger.LogInformation("{ControllerName}.{MethodName} action get method",
                nameof(UserController), nameof(this.RoleManagement));

            if (userId == null)
            {
                return this.NotFound();
            }

            var role = await this._db.UserRoles.FirstOrDefaultAsync
                (u => u.UserId == userId);
            var roleId = role?.RoleId;

            var roleVM = new RoleManagementVM()
            {
                ApplicationUser = await this._db.ApplicationUsers.Include(u => u.Company).FirstOrDefaultAsync
                    (u => u.Id == userId),
                RoleList = this._db.Roles.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Name
                }),
                CompanyList = this._db.Companies.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
            };

            if (roleVM.ApplicationUser != null)
            {
                roleVM.ApplicationUser.Role = _db.Roles.FirstOrDefault
                    (u => u.Id == roleId)?.Name;
            }

            return this.View(roleVM);
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> RoleManagement
            ([FromForm] RoleManagementVM roleManagementVM)
        {
            var roleID = this._db.UserRoles.FirstOrDefault
                (u => u.UserId == roleManagementVM.ApplicationUser.Id)?.RoleId;
            var oldRole = _db.Roles.FirstOrDefault(u => u.Id == roleID)?.Name;

            if (!(roleManagementVM.ApplicationUser?.Role == oldRole))
            {
                //a role was updated
                var applicationUser = await this._db.ApplicationUsers.FirstOrDefaultAsync
                    (u => u.Id == roleManagementVM.ApplicationUser.Id);
                if (roleManagementVM.ApplicationUser.Role == StaticDetails.Role_Company)
                {
                    applicationUser.CompanyId = roleManagementVM.ApplicationUser.CompanyId;
                }
                if (oldRole == StaticDetails.Role_Company)
                {
                    applicationUser.CompanyId = null;
                }
                _db.SaveChanges();

                _userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
                _userManager.AddToRoleAsync(applicationUser, roleManagementVM.ApplicationUser.Role).GetAwaiter().GetResult();

            }
            return RedirectToAction("Index");
        }

        #region API calls
        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> GetAllUsers()
        {
            this._logger.LogInformation("{ControllerName}.{MethodName} action get API method",
                nameof(UserController), nameof(this.GetAllUsers));

            var users = await this._db.ApplicationUsers
                .Include(u => u.Company).ToListAsync();

            var usersRoles = await this._db.UserRoles.ToListAsync();
            var roles = await this._db.Roles.ToListAsync();

            foreach (var user in users)
            {
                var roleId = usersRoles.FirstOrDefault(u => u.UserId == user.Id)?.RoleId;
                if (roleId == null)
                {
                    user.Role = "Didn't assign role yet";
                }
                else
                {
                    user.Role = roles.FirstOrDefault(r => r.Id == roleId)?.Name;
                }

                if (user.Company == null)
                {
                    user.Company = new Company();
                    user.Company.Name = string.Empty;
                }
            }

            return this.Json(new
            {
                Data = users
            });
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> LockUnlock([FromQuery] string? id)
        {
            this._logger.LogInformation("{ControllerName}.{MethodName} action POST API method",
                nameof(UserController), nameof(this.LockUnlock));

            var userFromDb = await this._db.ApplicationUsers.FirstOrDefaultAsync
                (u => u.Id == id);
            if (userFromDb == null)
            {
                return Json(new { success = false, message = "Error while Locking/Unlocking" });
            }

            if (userFromDb.LockoutEnd != null && userFromDb.LockoutEnd > DateTime.Now)
            {
                //user is currently locked and we need to unlock them
                userFromDb.LockoutEnd = DateTime.Now;
            }
            else
            {
                userFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }

            await this._db.SaveChangesAsync();

            return this.Json(new { success = true, message = "Lock/Unlock User Successful" });
        }
        #endregion
    }
}

BooksStore.Web/ViewComponents/ShoppingCartViewComponent.cs
using BooksStore.DataAccess.Repositories.IRepositories;
using BooksStore.Utilities;
using BooksStore.Web.Areas.Customer.Controllers;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BooksStore.Web.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        private ILogger<ShoppingCartViewComponent> _logger;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork, ILogger<ShoppingCartViewComponent> logger)
        {
            this._unitOfWork = unitOfWork;
            this._logger = logger;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            this._logger.LogInformation("{ControllerName}.{MethodName} view component",
                nameof(ShoppingCartViewComponent), nameof(this.InvokeAsync));

            var claimsIdentity = (ClaimsIdentity?)this.User.Identity;
            var claim = claimsIdentity?.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claimsIdentity?.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                var shoppingCarts = await this._unitOfWork.ShoppingCarts.GetAll
                    (s => s.ApplicationUserId == userId);

                if(this.HttpContext.Session.GetInt32(StaticDetails.SessionCart) == null)
                {
                    this.HttpContext.Session.SetInt32(StaticDetails.SessionCart,
                        ShoppingOrdersHelping.GetTotalOrders(shoppingCarts));
                }

                return this.View(this.HttpContext.Session.GetInt32(StaticDetails.SessionCart));
            }
            else
            {
                this.HttpContext.Session.Clear();

                return this.View(0);
            }
        }
    }
}

BooksStore.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bulky Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/BooksStore.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
                    <img src="/images/book.png" style="width:30px" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(StaticDetails.Role_Admin) || User.IsInRole(StaticDetails.Role_Employee) || User.IsInRole(StaticDetails.Role_Company) || User.IsInRole(StaticDetails.Role_Customer))
                        {                      
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manager Order</a>
                            </li>
                        }
                        @if (User.IsInRole(StaticDetails.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Managment
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">
                                            Category
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">
                                            Product
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">
                                            Company
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                </ul>
                            </li>
                        }
                        @if (HttpContextAccessor?.HttpContext?.Session.GetInt32(StaticDetails.SessionCart) != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    @await Component.InvokeAsync("ShoppingCart")
                                    @* <i class="bi bi-cart"></i> &nbsp;
                                    (@HttpContextAccessor.HttpContext.Session.GetInt32(StaticDetails.SessionCart)) *@
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    <i class="bi bi-cart"></i> &nbsp;
                                    (0)
                                </a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 mb-5">
            <partial name="_Notification.cshtml" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="text-center">
            Made with <i class="bi bi-heart-fill"></i> by Zin Team
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/g28lhnxtlihu4l4a381gw7tz47voznshwbi10lmsvlekrfme/tinymce/6/tinymce.min.js" referrerpolicy="origin">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BooksStore.Web/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success("@TempData["Success"]");
    </script>
}

@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error("@TempData["Error"]?.ToString()");
    </script>
}